apiVersion: apps/v1
kind: Deployment
metadata:
  name: regulaai-api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: regulaai-api
  template:
    metadata:
      labels:
        app: regulaai-api
    spec:
      containers:
        - name: api
          image: {{ .Values.api.image }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          env:
            {{- toYaml .Values.api.env | nindent 12 }}
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: regulaai-api
spec:
  selector:
    app: regulaai-api
  ports:
    - port: 80
      targetPort: 8000 