apiVersion: apps/v1
kind: Deployment
metadata:
  name: regulaai-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regulaai-postgres
  template:
    metadata:
      labels:
        app: regulaai-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          env:
            {{- toYaml .Values.postgres.env | nindent 12 }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: regulaai-postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: regulaai-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: regulaai-postgres
spec:
  selector:
    app: regulaai-postgres
  ports:
    - port: 5432
      targetPort: 5432 