apiVersion: apps/v1
kind: Deployment
metadata:
  name: regulaai-worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: regulaai-worker
  template:
    metadata:
      labels:
        app: regulaai-worker
    spec:
      containers:
        - name: worker
          image: {{ .Values.worker.image }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          env:
            {{- toYaml .Values.worker.env | nindent 12 }}
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: regulaai-worker
spec:
  selector:
    app: regulaai-worker
  ports:
    - port: 80
      targetPort: 8001 