api:
  image: "regulaai-api:latest"
  replicas: 2
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  env:
    - name: DATABASE_URL
      value: "postgresql://postgres:postgres@regulaai-postgres:5432/regulaai"
    - name: JWT_SECRET_KEY
      value: "changeme"

worker:
  image: "regulaai-worker:latest"
  replicas: 2
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  env:
    - name: DATABASE_URL
      value: "postgresql://postgres:postgres@regulaai-postgres:5432/regulaai"

postgres:
  image: "postgres:15"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  env:
    - name: POSTGRES_DB
      value: "regulaai"
    - name: POSTGRES_USER
      value: "postgres"
    - name: POSTGRES_PASSWORD
      value: "postgres"
  storage:
    size: 5Gi

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: "regulaai.local"
      paths:
        - "/"
  tls:
    - secretName: "regulaai-tls"
      hosts:
        - "regulaai.local" 