"""Use server_default for plan and remaining_scans_month in Organisation

Revision ID: 4724cfa42642
Revises: 74f351a9d56c
Create Date: 2025-06-18 16:31:24.068796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4724cfa42642'
down_revision: Union[str, None] = '74f351a9d56c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
