"""Add integration fields to organisations

Revision ID: 5198620ac08e
Revises: da954ee35e1e
Create Date: 2025-06-18 20:12:47.937697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5198620ac08e'
down_revision: Union[str, None] = 'da954ee35e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisations', sa.Column('slack_webhook_url', sa.String(length=500), nullable=True))
    op.add_column('organisations', sa.Column('resend_api_key', sa.String(length=255), nullable=True))
    op.add_column('organisations', sa.Column('notification_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisations', 'notification_email')
    op.drop_column('organisations', 'resend_api_key')
    op.drop_column('organisations', 'slack_webhook_url')
    # ### end Alembic commands ###
